# Generated by Django 4.2 on 2023-04-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcommentmodel',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterUniqueTogether(
            name='productcommentmodel',
            unique_together={('userID', 'productID')},
        ),
    ]
