name: Microservice CI/CD pipeline

on:  
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build user
        run:  |
          docker build ./User -t lilian/user:1.0.0
